-- Ensure ESPLORA_LIKE and ESPLORA_COMMENT types exist in the enum
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ESPLORA_LIKE';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'ESPLORA_COMMENT';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'EVENT_REMOVE';
